### ISSUE TITLE
Manual creation of Doors cause issues

### ISSUE THREAD

**Issue by bravery3000** [OndrejNepozitek/Edgar-Unity#79]
Hi, 

I'm trying to build a simple room and corridor, where I have created one single square room and add only one door tile at each side  of the room, and create another corridor template and specify one time at each end of the corridor.

Now when I run the level generator I got the below error, please advise how to fix this:

InvalidOperationException: Timeout was reached when generating level
ProceduralLevelGenerator.Unity.Generators.DungeonGenerator.PipelineTasks.DungeonGeneratorTask`1+<Process>d__2[TPayload].MoveNext () (at Assets/ProceduralLevelGenerator/Runtime/Generators/DungeonGenerator/PipelineTasks/DungeonGeneratorTask.cs:86)
ProceduralLevelGenerator.Unity.Pipeline.PipelineRunner`1+<GetEnumerator>d__1[TPayload].MoveNext () (at Assets/ProceduralLevelGenerator/Runtime/Pipeline/PipelineRunner.cs:29)
ProceduralLevelGenerator.Unity.Pipeline.PipelineRunner`1[TPayload].Run (System.Collections.Generic.IEnumerable`1[T] pipelineTasks, TPayload payload) (at Assets/ProceduralLevelGenerator/Runtime/Pipeline/PipelineRunner.cs:16)
ProceduralLevelGenerator.Unity.Generators.Common.LevelGeneratorBase`1[TPayload].Generate () (at Assets/ProceduralLevelGenerator/Runtime/Generators/Common/LevelGeneratorBase.cs:41)
ProceduralLevelGenerator.Unity.Editor.LevelGenerators.DungeonGeneratorInspector.OnInspectorGUI () (at Assets/ProceduralLevelGenerator/Editor/LevelGenerators/DungeonGeneratorInspector.cs:65)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass55_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <90d4bcb003fb405fb09241aed2f178aa>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by OndrejNepozitek** [comment]
Hey!
The timeout error usually that there's something wrong with your room templates. For example, the generator might be unable to produce a level if there's no way to connect two neighbouring rooms. That can be caused for example if you accidentally use different lengths of doors.

Please do the following: There is an "Advanced" section in the Dungeon Generator component and there should be an "Export map description" button. Click the button and it should create a file called "exportedMapDescription.json" in the root folder of your project. Please send me this file - it contains information about the shapes of your rooms. (In order to attach the file to this issue, you have to convert it to a txt file). I'll look into that file so we can solve the issue.

**Comment by bravery3000** [comment]
Hi Onder, 
and thanks for the quick reply, here is the content of the file:

[exportedMapDescription.txt](https://github.com/OndrejNepozitek/Edgar-Unity/files/5397596/exportedMapDescription.txt)

**Comment by OndrejNepozitek** [comment]
From the file that you sent me, it seems to me that you only have a single corridor room template. If I'm reading the file properly, the corridor room template is vertical - it can connect two rooms if one of the rooms is above the other room. The problem is that your level graph seems to be a cycle which is impossible to generate using only vertical corridors. Please create a second corridor room template so you can connect rooms both horizontally and vertically.

Let me know if it helps!

**Comment by bravery3000** [comment]
Yep that did the trick thank you :)
