### ISSUE TITLE
Can't add manual doors

### ISSUE THREAD

**Issue by burakomer** [OndrejNepozitek/Edgar-Unity#84]
Unity 2019.4.14f1
Edgar v2.0.0-alpha.6

I suddenly can't add manual doors. When I activate **Add door positions** button, it simply doesn't do anything, the previous tool selected functions. I don't know how it happened.

**Comment by OndrejNepozitek** [comment]
Hey!
Please check that there are no Unity tools interfering with the process of adding manual doors. For example, one problem that I sometimes encounter is when I do some drawing with the Tile Palette window and then want to add manual door positions. Sometimes, the tool that I have selected in the Tile Palette prevents me from adding door positions. So I go back and choose the left-most option (Select an area of the grid) and try again to add doors. Unfortunately, I cannot do anything with this from inside the asset because Unity does not have an API to control that.

So my advice is to check that you don't have any weird tool activated in Unity that would prevent the asset from registering mouse clicks in order to add doors.

If that doesn't help, we can look into that further. However, I used this functionality today and it worked for me.

**Comment by burakomer** [comment]
Alright, second restart fixed it. For the record, selecting the tool you mentioned did nothing. I had a second Inspector window, maybe that was the issue, though I don't know because it didn't get fixed right away after closing the second Inspector.

**Comment by OndrejNepozitek** [comment]
That's good to hear. If you ever manage to replicate the behaviour that leads to your problem, let me know and I'll try looking into that.
