### ISSUE TITLE
Corridor.Door.FacingDir bug?

### ISSUE THREAD

**Issue by longtran2904** [OndrejNepozitek/Edgar-Unity#88]
The facing direction is opposite in a corridor. I print the facingDir and DoorLine.From to the console and here the result:
![image](https://user-images.githubusercontent.com/53656110/100446254-0d122580-30e1-11eb-8037-6586433bd7d4.png)
The corridor number is the instance id to make sure that it on the same corridor. The facingDir of the first door is left but the x position of it is greater than the second one (it actually is on the right).

**Comment by OndrejNepozitek** [comment]
You're correct. It seems like this is a bug in the DotNet version of the generator and should be fixed there. Can you work around this problem or is it a blocker for you? If it's a blocker for you, I can probably come up with a hotfix for you, otherwise, I'll fix it in the next release.

**Comment by longtran2904** [comment]
I just multiply with -1 for now. Haven't seen any problems so far.

**Comment by longtran2904** [comment]
Is there any way I can fix this now? Just multiply with -1 is not an ideal solution and I fear that I will forget to change it back when you fix it (also it is not really readable).

**Comment by longtran2904** [comment]
Also if a room has one door then it showed correctly.

**Comment by OndrejNepozitek** [comment]
You can probably implement the logic yourself. If you know that there are always two doors in a corridor, you can first check whether the corridor is vertical or horizontal (assuming that you only have straight corridors) and then check the coordinates. If you have a horizontal corridor then you know that the door with the smallest x is facing to the left and the other door is facing to the right.

Unfortunately, I currently don't have enough time to implement this myself. I hope to fix that sometime later this week.

**Comment by OndrejNepozitek** [comment]
It should now be fixed in the dev branch. Can you please try that?

If you know how to update the whole asset from a github branch, you can that based on the current state of the dev branch. The second option is to update only the single file that was changed. Download the EdgarSingleFile.dll file from [here](https://github.com/OndrejNepozitek/Edgar-Unity/blob/3d9d154f439b8bd209f05c902a77ac0aac96128c/Libraries/EdgarSingleFile.dll) and put it inside Assets/Edgar/Libraries (overwrite the old file).

Let me know if that works.

**Comment by longtran2904** [comment]
Sorry for the late reply. Been busy lately. Tried the fix for a couple of days and it works fine so far. Thanks!
