### ISSUE TITLE
Enemies stuck in the ground....

### ISSUE THREAD

**Issue by CaribeAtomic** [OndrejNepozitek/Edgar-Unity#94]
Hello, I have the problem of when the level is generated, some enemies appear stuck on the floor. happens with the random enemy.

Can you see the image attached

![image](https://user-images.githubusercontent.com/75189542/106074152-57138980-60d9-11eb-8ef5-61a5f693e04b.png)

**Comment by OndrejNepozitek** [comment]
Hey! Can you please confirm that you have performed the following two steps that are necessary to run the example?

> To run the example, you need to:
> 
> Add a layer called "StaticEnvironment"
> Enable "Auto Sync Transforms" in Physics2D settings

**Comment by CaribeAtomic** [comment]
Yes!! I did it.
If I don't do that, the map won't be generated

**Comment by OndrejNepozitek** [comment]
I investigated the issues and it seems like there's a problem with one of the enemy spawn points - it's positioned too low and cause the enemy to get stuck. If you want to fix that, please go to DeadCells/Underground/Room templates/Room 5. In that prefab, go to EnemySpawnPoints -> GameObject (1) and change its Y position to -7. I'll include an official fix in the next version.

Also, it seems like enemies sometimes render behind some tiles because of a missing sorting layer. If you want to hotfix that too, go to DeadCells/Prefabs/Enemy 1 and 2 and change the Order in Layer in their sprite renderers to something like 8,´. I'll include this in the next version, too.

Thanks for reporting the issue.
