### ISSUE TITLE
Newtonsoft JSON DLL conflict

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [OndrejNepozitek/Edgar-Unity#95]
This package bundles a `Newtonsoft.Json.dll` for itself, which conflicts with `Newtonsoft.Json.dll` from other packages like "Json.NET for Unity".

This package should depend on that package so that there is no conflicts.

**Comment by OndrejNepozitek** [comment]
Hey, which version of Edgar do you use? `Newtonsoft.Json.dll` is used as a dependency of the .NET generator - Edgar-DotNet. However, this library is for some time now included as a single DLL - `EdgarSingleFile.dll` - and `Newtonsoft.Json.dll` should be marked as internal in this library, i.e. not visible to the outside world. I tried adding a copy of `Newtonsoft.Json.dll` to a project alongside Edgar and got no errors.

Can you please confirm that you're using the latest version of Edgar? If you recently updated from an older version of Edgar, there could be a problem with some old unused files remaining in your project.

**Comment by ColonelThirtyTwo** [comment]
I used the one off of OpenUPM here: https://openupm.com/packages/com.ondrejnepozitek.procedurallevelgenerator/ . Says the latest version is `2.0.0-alpha.5`. I'll check what exact version I'm using when I get off work.

**Comment by OndrejNepozitek** [comment]
It seems like the version on OpenUPM is no longer up to date. Some time ago, I decided to go from the old generic "procedurallevelgenerator" name to the name "Edgar" and this change is not reflected on OpenUPM and was also not reflected in the readme. I'm sorry about that. Please use this package now to get the latest version:
```
 "com.ondrejnepozitek.edgar.unity": "https://github.com/OndrejNepozitek/Edgar-Unity.git#upm"
```
The problem with `Newtonsoft.Json.dll` should be fixed there.

I hope that there are no other problems with the UPM version. Unfortunately, it's quite hard for me to keep that version up-to-date because the structure of the project has to be slightly different because of how are example scenes done inside UPM projects, which in turn breaks all automatic tests. So if you find any other problems, please let me know and I'll try to fix them as soon as possible.
