### ISSUE TITLE
Secret rooms

### ISSUE THREAD

**Issue by pvalium** [OndrejNepozitek/Edgar-Unity#99]
Hi. Is posible to hide/show certain rooms via code?
I want to add secret rooms that are invisible (the door, is a wall), but player can enable/show them via a button.

**Comment by pvalium** [comment]
Well, so far I have achieved it using an extra tilemap, and some fixes in corridors, and runs ok.

**Comment by OndrejNepozitek** [comment]
Hey, that's great that you managed to come up with something.

Somebody has asked me a similar quite before so I've already thought about it a little. Basically, the goal would be to combine this with the Fog of War feature. You'd mark a room as hidden and that would instruct the generator to hide it via the FoW and also to not remove the walls from neighbouring rooms. Then if you triggered some action to reveal the room, the generator would first remove the blocking walls and then reveal the room.

I also thought about adding custom door blockers for example if you wanted to have a special game object present at the secret room entrance, etc. So instead of just not removing the tiles from the connection to the neighbouring room, the generator would instead spawn the predefined blocker tiles/objects.

Are you happy with your current solution or is there anything I can help you with?

**Comment by pvalium** [comment]
Yes, my solution its ok for me.
Thank you anyway!
